from __future__ import annotations

import random


SUPPORTED_LANGUAGES = {"tr", "en"}

ELEMENT_LABELS = {
    "tr": {
        "fire": "ateş",
        "earth": "toprak",
        "air": "hava",
        "water": "su",
    },
    "en": {
        "fire": "fire",
        "earth": "earth",
        "air": "air",
        "water": "water",
    },
}

WORD_TRANSLATIONS_EN = {
    "Adalet": "Justice",
    "Adaptasyon": "Adaptation",
    "Affediş": "Forgiveness",
    "Ahengi Bulma": "Finding Harmony",
    "Aidiyet": "Belonging",
    "Aile": "Family",
    "Akış": "Flow",
    "Akışa Güven": "Trust in Flow",
    "Akrep": "Scorpio",
    "Aksiyon": "Action",
    "Alev": "Flame",
    "Analiz": "Analysis",
    "Anlam": "Meaning",
    "Anlatı": "Narrative",
    "Arayış": "Seeking",
    "Araştırma": "Inquiry",
    "Arınma": "Purification",
    "Arıtma": "Cleansing",
    "Arka Plan": "Background",
    "Aslan": "Leo",
    "At": "Horse",
    "Atak": "Bold Move",
    "Ateş": "Fire",
    "Ateş Çemberi": "Circle of Fire",
    "Ateşli Odak": "Fiery Focus",
    "Ateşli Vizyon": "Fiery Vision",
    "Atılım": "Breakthrough",
    "Ayna": "Mirror",
    "Azim": "Determination",
    "Açık Pencere": "Open Window",
    "Açıklık": "Openness",
    "Açılım": "Opening",
    "Ağaç": "Wood",
    "Bakım": "Care",
    "Bakış Açısı": "Perspective",
    "Balık": "Pisces",
    "Barış": "Peace",
    "Bağlantı": "Connection",
    "Bağışlama": "Forgiveness",
    "Bağımsızlık": "Independence",
    "Başak": "Virgo",
    "Başarı": "Success",
    "Başlangıç": "Beginning",
    "Başlatma": "Initiation",
    "Beden": "Body",
    "Bekçilik": "Guardianship",
    "Bereket": "Abundance",
    "Besleme": "Nurturing",
    "Bilgelik": "Wisdom",
    "Bolluk": "Plenty",
    "Boğa": "Taurus",
    "Büyüme": "Growth",
    "Bırakış": "Release",
    "Canlanma": "Revival",
    "Canlılık": "Vitality",
    "Cesaret": "Courage",
    "Cesur İfade": "Brave Expression",
    "Coşku": "Enthusiasm",
    "Cömertlik": "Generosity",
    "Dalga": "Wave",
    "Dayanak": "Support",
    "Dayanıklılık": "Resilience",
    "Deney": "Experiment",
    "Deneyim": "Experience",
    "Denge": "Balance",
    "Dengeleme": "Balancing",
    "Deri Değişimi": "Shedding Skin",
    "Derin Görüş": "Deep Sight",
    "Derinleşme": "Deepening",
    "Derinlik": "Depth",
    "Derlenme": "Gathering Back",
    "Detay": "Detail",
    "Değer": "Value",
    "Değişim": "Change",
    "Dikkat": "Attention",
    "Dinleme": "Listening",
    "Diplomasi": "Diplomacy",
    "Diriliş": "Resurrection",
    "Disiplin": "Discipline",
    "Diyalog": "Dialogue",
    "Domuz": "Pig",
    "Dostluk": "Friendship",
    "Duyarlılık": "Sensitivity",
    "Duygu": "Emotion",
    "Duygusal Netlik": "Emotional Clarity",
    "Duruş": "Stance",
    "Dönüşüm": "Transformation",
    "Dürüst Çıkış": "Honest Emergence",
    "Dürüstlük": "Honesty",
    "Düşünce": "Thought",
    "Düzen": "Order",
    "Ejderha": "Dragon",
    "Elektrik": "Electricity",
    "Emek": "Effort",
    "Empati": "Empathy",
    "Enerji": "Energy",
    "Enerji Patlaması": "Burst of Energy",
    "Esneklik": "Flexibility",
    "Estetik": "Aesthetics",
    "Etki": "Impact",
    "Evrensellik": "Universality",
    "Eylem": "Action",
    "Eşitlik": "Equity",
    "Eşik": "Threshold",
    "Farklılık": "Difference",
    "Farkındalık": "Awareness",
    "Fikir": "Idea",
    "Filiz": "Sprout",
    "Fırsat": "Opportunity",
    "Gelecek": "Future",
    "Genişleme": "Expansion",
    "Gizem": "Mystery",
    "Gölge": "Shadow",
    "Gölgeyle Barış": "Peace with Shadow",
    "Görkem": "Splendor",
    "Görünürlük": "Visibility",
    "Gözlem": "Observation",
    "Gözükaralık": "Daring",
    "Güven": "Trust",
    "Güvenli Alan": "Safe Space",
    "Güzellik": "Beauty",
    "Güç": "Power",
    "Haber": "Message",
    "Hafifleme": "Lightening",
    "Hafıza": "Memory",
    "Hamle": "Move",
    "Hareket": "Movement",
    "Harita": "Map",
    "Hassasiyet": "Sensitivity",
    "Hassas Ölçü": "Fine Measure",
    "Hayal": "Dream",
    "Haz": "Pleasure",
    "Hedef": "Goal",
    "Hizmet": "Service",
    "Horoz": "Rooster",
    "Huzur": "Calm",
    "Hız": "Speed",
    "Isı": "Heat",
    "Işık": "Light",
    "Kabuk": "Shell",
    "Kabul": "Acceptance",
    "Kabulleniş": "Acceptance",
    "Kader": "Fate",
    "Kader Hamlesi": "Move of Fate",
    "Kalp": "Heart",
    "Kalp Bağı": "Heart Bond",
    "Kalp Gücü": "Heart Strength",
    "Kalp Suyu": "Heart Water",
    "Kalıcılık": "Permanence",
    "Kalkış": "Lift-Off",
    "Kapanış": "Closure",
    "Kaplan": "Tiger",
    "Karar": "Decision",
    "Kararlılık": "Resolve",
    "Karşılaşma": "Encounter",
    "Kazanma": "Winning",
    "Kendini Yakma": "Self-Ignition",
    "Keskinlik": "Sharpness",
    "Keçi": "Goat",
    "Keşif": "Discovery",
    "Kimlik": "Identity",
    "Konfor": "Comfort",
    "Konsantrasyon": "Concentration",
    "Koruma": "Protection",
    "Korumak": "Protecting",
    "Kova": "Aquarius",
    "Koç": "Aries",
    "Krallık": "Sovereignty",
    "Kriz Bilgeliği": "Crisis Wisdom",
    "Kök": "Root",
    "Kök Hafızası": "Root Memory",
    "Köklenme": "Rooting",
    "Köklülük": "Rootedness",
    "Köpek": "Dog",
    "Köprü": "Bridge",
    "Kırılganlık": "Vulnerability",
    "Kırılma Anı": "Turning Point",
    "Kıvraklık": "Agility",
    "Kıvranış": "Restless Stirring",
    "Kıvılcım": "Spark",
    "Liderlik": "Leadership",
    "Macera": "Adventure",
    "Manyetizma": "Magnetism",
    "Maymun": "Monkey",
    "Merak": "Curiosity",
    "Merhamet": "Compassion",
    "Merkez": "Center",
    "Metal": "Metal",
    "Meydan Okuma": "Challenge",
    "Mistiklik": "Mysticism",
    "Mizah": "Humor",
    "Motivasyon": "Motivation",
    "Mücadele": "Struggle",
    "Nefes": "Breath",
    "Netlik": "Clarity",
    "Neşe": "Joy",
    "Odak": "Focus",
    "Olgunlaşma": "Ripening",
    "Olgunluk": "Maturity",
    "Ortaklık": "Partnership",
    "Otorite": "Authority",
    "Oyun": "Play",
    "Oğlak": "Capricorn",
    "Parlama": "Radiance",
    "Parlamak": "Shining",
    "Paylaşım": "Sharing",
    "Perspektif": "Perspective",
    "Plan": "Plan",
    "Planlama": "Planning",
    "Pratiklik": "Practicality",
    "Problem Çözme": "Problem Solving",
    "Rahatlık": "Ease",
    "Renk": "Color",
    "Risk": "Risk",
    "Ritim": "Rhythm",
    "Ruh Hafızası": "Soul Memory",
    "Ruhsal Dinlenme": "Spiritual Rest",
    "Ruhsal Odak": "Spiritual Focus",
    "Rutin": "Routine",
    "Rüya": "Dream",
    "Rüzgar": "Wind",
    "Sabitleme": "Anchoring",
    "Sabır": "Patience",
    "Sadakat": "Loyalty",
    "Sadelik": "Simplicity",
    "Sahne": "Stage",
    "Sakin Güç": "Calm Strength",
    "Sakinleşme": "Calming",
    "Sakinlik": "Stillness",
    "Saklı Bilgi": "Hidden Knowledge",
    "Samimiyet": "Sincerity",
    "Sanat": "Art",
    "Sebat": "Perseverance",
    "Sessiz Bilgi": "Silent Knowledge",
    "Sessiz Sabır": "Silent Patience",
    "Sessiz Şifa": "Silent Healing",
    "Sessizlik": "Silence",
    "Sezgi": "Intuition",
    "Sezme": "Sensing",
    "Seçenek": "Option",
    "Seçicilik": "Discernment",
    "Sistem": "System",
    "Sistem Kırma": "Pattern Breaking",
    "Somut Adım": "Concrete Step",
    "Somutlaşma": "Materialization",
    "Somutluk": "Tangibility",
    "Sonuç": "Outcome",
    "Sorgulama": "Questioning",
    "Soru": "Question",
    "Sorumluluk": "Responsibility",
    "Stabilite": "Stability",
    "Strateji": "Strategy",
    "Su": "Water",
    "Suların Yolu": "The Way of Waters",
    "Söz": "Word",
    "Sükunet": "Serenity",
    "Süreklilik": "Continuity",
    "Sınır": "Boundary",
    "Sınır Çözülmesi": "Dissolving Boundaries",
    "Sır": "Secret",
    "Sızıntı": "Seepage",
    "Sıçan": "Rat",
    "Sıçrama": "Leap",
    "Tamamlanma": "Completion",
    "Tutarlı Hamle": "Consistent Move",
    "Tavşan": "Rabbit",
    "Tazelenme": "Renewal",
    "Taşıma": "Carrying",
    "Taşıyıcılık": "Holding",
    "Taş Gibi Netlik": "Stone-Like Clarity",
    "Teklik": "Oneness",
    "Temel": "Foundation",
    "Temizlik": "Cleansing",
    "Terazi": "Libra",
    "Teslimiyet": "Surrender",
    "Toplanma": "Gathering",
    "Topluluk": "Community",
    "Toprak": "Earth",
    "Topraklanma": "Grounding",
    "Toparlanma": "Regathering",
    "Tutku": "Passion",
    "Ufuk": "Horizon",
    "Ustalık": "Mastery",
    "Uyanış": "Awakening",
    "Uyum": "Harmony",
    "Uyumlanma": "Attunement",
    "Uzak Görüş": "Long View",
    "Vahşi Güç": "Wild Power",
    "Vefa": "Devotion",
    "Verim": "Productivity",
    "Vizyon": "Vision",
    "Yakınlık": "Closeness",
    "Yapı": "Structure",
    "Yapı Kurma": "Building Structure",
    "Yaratıcılık": "Creativity",
    "Yay": "Sagittarius",
    "Yengeç": "Cancer",
    "Yeniden Çerçeve": "Reframing",
    "Yeniden Doğuş": "Rebirth",
    "Yenilenme": "Renewal",
    "Yol": "Path",
    "Yolculuk": "Journey",
    "Yoğunluk": "Intensity",
    "Yumuşaklık": "Softness",
    "Yumuşama": "Softening",
    "Yuva": "Home",
    "Yön": "Direction",
    "Yön Bulma": "Finding Direction",
    "Yön Değişimi": "Change of Direction",
    "Yönetim": "Management",
    "Yükseliş": "Rise",
    "Yılan": "Snake",
    "Yavaş Güç": "Slow Strength",
    "Yavaş Çözülme": "Slow Dissolving",
    "Zarafet": "Grace",
    "Zarif Uyum": "Graceful Harmony",
    "Zeka": "Intelligence",
    "Zerafet": "Grace",
    "Zemin": "Ground",
    "Zihin": "Mind",
    "Zihin Işığı": "Mind Light",
    "Zihinsel Açılım": "Mental Opening",
    "Zihinsel Temizlik": "Mental Clearing",
    "Zirve": "Peak",
    "Çağrı": "Calling",
    "Çeviklik": "Agility",
    "Öküz": "Ox",
    "Ölçü": "Measure",
    "Öncülük": "Pioneering",
    "Özen": "Care",
    "Özgünlük": "Originality",
    "Özgürlük": "Freedom",
    "Özgüven": "Self-Confidence",
    "Öğrenme": "Learning",
    "Üretim": "Production",
    "İddia": "Assertion",
    "İfade": "Expression",
    "İlk Adım": "First Step",
    "İkizler": "Gemini",
    "İlan": "Declaration",
    "İletişim": "Communication",
    "İlham": "Inspiration",
    "İlişki": "Relationship",
    "İnanç": "Faith",
    "İnce Ayar": "Fine Tuning",
    "İnce Sezgi": "Subtle Intuition",
    "İncelik": "Subtlety",
    "İnisiyatif": "Initiative",
    "İnovasyon": "Innovation",
    "İnşa": "Building",
    "İrade": "Will",
    "İstikrar": "Stability",
    "İyi Niyet": "Goodwill",
    "İyileşme": "Healing",
    "İyileştirme": "Improvement",
    "İç Deniz": "Inner Sea",
    "İç Disiplin": "Inner Discipline",
    "İç Motor": "Inner Engine",
    "İç Ses": "Inner Voice",
    "İç Temizlik": "Inner Cleansing",
    "İçgörü": "Insight",
    "İçsel Uyum": "Inner Harmony",
    "İşaret": "Sign",
    "İşbirliği": "Collaboration",
    "Şans": "Luck",
    "Şefkat": "Tenderness",
    "Şifa": "Healing",
}


def normalize_language(language: str | None) -> str:
    if not language:
        return "tr"
    normalized = language.strip().lower()
    return normalized if normalized in SUPPORTED_LANGUAGES else "tr"


def localize_word(word: str, language: str) -> str:
    if normalize_language(language) == "en":
        return WORD_TRANSLATIONS_EN.get(word, word)
    return word


def localize_element(element_key: str, language: str) -> str:
    language = normalize_language(language)
    return ELEMENT_LABELS.get(language, ELEMENT_LABELS["tr"]).get(element_key, "earth")


def build_localized_motto(word1: str, energy_word: str, element_key: str, language: str) -> str:
    language = normalize_language(language)
    element_label = localize_element(element_key, language)

    if language == "en":
        templates = [
            "Today {energy} awakens your {element} energy, while {corner} remains your compass.",
            "{energy} is moving through your field today; {corner} stays at the center of each step.",
            "The sky speaks in a {element} tone today: {energy} calls you, {corner} steadies your path.",
            "Today's current is {energy}; with {corner}, you rewrite your own story.",
        ]
    else:
        templates = [
            "Bugün {energy} senin {element} enerjini uyandırırken, {corner} pusulan olmaya devam ediyor.",
            "{energy} enerjisi bugün alanında; {corner} ise attığın her adımın merkezinde.",
            "Gökyüzü bugün {element} tınısında: {energy} seni çağırıyor, {corner} rotanı sabitliyor.",
            "Bugünün akışı {energy}; sen {corner} ile kendi hikâyeni yeniden yazıyorsun.",
        ]

    seed_str = f"{word1}-{energy_word}-{element_key}-{language}"
    rnd = random.Random(seed_str)
    template = templates[rnd.randint(0, len(templates) - 1)]

    return template.format(
        energy=energy_word,
        corner=word1,
        element=element_label,
    )
